### ISSUE TITLE
[Add Component]: Add an Animated Button

### ISSUE THREAD

**Issue by ketan-sonar** [pccoe-acm-hacktoberfest-2023/animated-components#1]
# Description

- Add an Animated Button Component.  
- Make sure to follow everything given in the CONTRIBUTING.md file

**Comment by AbdullahTheDev** [comment]
Can you assign this task to me? under hacktoberfest label?

**Comment by AryaKale16** [comment]
Hey @ketan-sonar,
I am good with stylings and animation, checkout my website [link](http://aryakale.me/), kindly consider assigning this issue to me.
